# Este workflow ejecuta únicamente las pruebas unitarias (TDD) con Maven
name: Test de Spring Boot (TDD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4
      
    - name: Configuracion JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar tests con Maven
      run: mvn -B test --file pom.xml
